version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_HOST}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: rise-cloud-node
    ports:
    - "13000:8000"
    depends_on:
    - db